import "./globals.css";
import { SesstionCover } from "./components/Session";
import Provider from "./store/providers/ReduxProvider";
import Sidebar from "./components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning className="min-h-screen flex bg-black text-white antialiased">
        <Provider>
        <Sidebar/>
        <SesstionCover>
          <main className="flex-1 flex flex-col min-h-screen overflow-y-auto">
            {children}
          </main>
        </SesstionCover>
        </Provider>
      </body>
    </html>
  );
}
