import "./globals.css";
import { SesstionCover } from "./components/Session";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning className="min-h-full flex flex-col">
        <SesstionCover>
          {children}
        </SesstionCover>
      </body>
    </html>
  );
}
